language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env:
        - FOR=linux-trusty-clang
    - os: linux
      dist: precise
      sudo: required
      env:
        - FOR=linux-precise-gcc
    - os: osx
      env:
        - FOR=osx

before_install:
- BuildResources/CI/before_install.sh

before_script:
- mkdir -p ThirdParty/libxml2/m4
- autoreconf -fvi

script:
- ./configure && make && make check
