language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required
    - os: macosx
compiler: clang
before_install:
- sudo apt-get install -qq build-essential clang binutils automake autoconf libtool pkg-config
- git clone --depth=50 --branch=develop https://github.com/TaliskerPlatform/idl.git
- cd idl && git submodule update --init --recursive && autoreconf -fvi && ./configure && make && sudo make install && cd ..
before_script:
- autoreconf -fvi
script:
- ./configure && make && make check
