language: c
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: linux
      dist: precise
      sudo: required
    - os: macosx
before_install:
- Resources/Travis/before_install.sh
before_script:
- autoreconf -fvi
script:
- ./configure && make && make check
