#! /bin/sh

## Talisker: Foundation Toolkit

## Copyright 2012-2017 Mo McRoberts.
##
##  Licensed under the Apache License, Version 2.0 (the "License");
##  you may not use this file except in compliance with the License.
##  You may obtain a copy of the License at
##
##      http://www.apache.org/licenses/LICENSE-2.0
##
##  Unless required by applicable law or agreed to in writing, software
##  distributed under the License is distributed on an "AS IS" BASIS,
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
##  See the License for the specific language governing permissions and
##  limitations under the License.

PACKAGE=FoundationKit

if ! test -r Resources/CI/mkdist 2>&1 ; then
	echo "This script must be executed from the root of the $PACKAGE source tree" >&2
	echo "and invoked as:" >&2
	echo "" >&2
	echo "Resources/CI/mkdist" >&2
	exit 1
fi

if test -r Makefile ; then
	make distclean
fi

OUTPUT="$PACKAGE-dist.tar"
test x"$1" = x"" || OUTPUT="$1"

rm -f filelist.dist filelist.cur
touch filelist.cur
find . -type f -print >>filelist.cur
grep -v -e '^\.$' -e '/\..*' \
	-e '\.o$' \
	-e '\.lo$' \
	-e '\.la$' \
	-e '\.so$' \
	-e '\.dylib$' \
	-e '\.dll$' \
	-e '\.exe$' \
	-e '\.tar$' \
	-e '\.tar\.' \
	-e '/filelist\.' \
	-e '/config\.status$' \
	-e '/autom4te\.cache$' -e '/autom4te\.cache/' \
	-e '\.log$' -e '\.trs$' -e '\.out$' -e '\.tmp$' -e '\.bak$' -e '~$' \
	<filelist.cur \
	>filelist.dist
rm -f filelist.cur
tar -c -f $OUTPUT.tmp -T filelist.dist
result=$?
rm -f filelist.dist
if test $result -ne 0 ; then
	rm -f $OUTPUT.tmp
	exit $?
fi
mv $OUTPUT.tmp $OUTPUT && echo "Created $OUTPUT" >&2
exit $?
